#!/usr/bin/env bash

set -e

SHELL='/bin/bash'
export SHELL

# Standard dotbot pre-configuration:

readonly DOTBOT_DIR='dotbot'
readonly DOTBOT_BIN='bin/dotbot'
readonly BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

readonly ARGS="$@"

cd "${BASEDIR}"
git submodule sync --quiet --recursive
git submodule update --init --recursive

run_dotbot () {
  local config
  config="$1"

  "$BASEDIR/$DOTBOT_DIR/$DOTBOT_BIN" \
    -d "$BASEDIR" \
    --plugin-dir dotbot-brewfile \
    -c "$config" $ARGS
}

run_dotbot 'steps/terminal.yaml' || true
run_dotbot 'steps/dependencies.yaml' || true
run_dotbot 'steps/vscode.yaml' || true
